apiVersion: v1
kind: Service
metadata:
  name: githubview-mongodb-service
spec:
  selector:
    app: githubview-mongodbapp
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
